### ISSUE TITLE
Why is a government college using .xlsx or Mircrosoft Excel instead of a open format like CSV?

### ISSUE THREAD

**Issue by Zerokami** [NIT-Warangal/Phone-Biller#1]
It looks like a simple spread sheet with basic values. One can use CSV.
I can only imagine how much they wasted on a Microsoft Office License.
# ClosedSourceIndia
# CrackInIndia
# OpenSourceMuch?
# IndiaAgainstOpenSource

**Comment by Logmytech** [comment]
Updated to add government

**Comment by sudheesh001** [comment]
The university has official licensing of the student versions from Microsoft in all labs and to all students. For any other issues please email, webmaster@nitw.ac.in
